services:
  - type: web
    name: rag-chatbot
    runtime: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: EMBEDDING_MODEL
        value: BAAI/bge-small-en
      - key: RERANKER_MODEL
        value: cross-encoder/ms-marco-MiniLM-L-6-v2
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: PYTHON_VERSION
        value: 3.11.9
